# Generated by Django 6.0.5 on 2026-05-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_view_count_post_posts_post_view_co_9cbe0c_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmedia',
            old_name='file',
            new_name='media',
        ),
    ]
