# Generated by Django 6.0.5 on 2026-05-07 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active'], name='profiles_pr_is_acti_032619_idx'),
        ),
    ]
