# Generated by Django 6.0.4 on 2026-04-10 21:13

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('target_value', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('reset_password', 'Reset Password')], max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='user_email_or_phone_required'),
        ),
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['target_value', 'purpose'], name='accounts_au_target__8be8be_idx'),
        ),
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['channel', 'target_value'], name='accounts_au_channel_5faa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['expires_at'], name='accounts_au_expires_65547d_idx'),
        ),
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['consumed_at'], name='accounts_au_consume_6bf541_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'is_revoked'], name='accounts_au_user_id_2e1f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['expires_at'], name='accounts_au_expires_7a274f_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['created_at'], name='accounts_au_created_841be7_idx'),
        ),
    ]
