# Generated by Django 6.0.5 on 2026-05-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authotp',
            name='accounts_au_target__8be8be_idx',
        ),
        migrations.RemoveIndex(
            model_name='authotp',
            name='accounts_au_channel_5faa5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='authotp',
            name='accounts_au_expires_65547d_idx',
        ),
        migrations.RemoveIndex(
            model_name='authotp',
            name='accounts_au_consume_6bf541_idx',
        ),
        migrations.DeleteModel(
            name='AuthOTP',
        ),
    ]
