# Generated by Django 6.0.5 on 2026-05-07 11:47

import django.db.models.deletion
import messaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('stories', '0002_storycomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecipientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_for_me_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messaging/group_images/'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.message_attachment_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_everyone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('story_reply', 'Story Reply')], db_index=True, default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation'], name='messaging_c_convers_5ef03b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'deleted_at'], name='messaging_m_convers_2f6430_idx'),
        ),
        migrations.AddField(
            model_name='messagerecipientstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagerecipientstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageuserstate',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messageuserstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagerecipientstatus',
            index=models.Index(fields=['message', 'user'], name='messaging_m_message_2b7d04_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipientstatus',
            index=models.Index(fields=['user', 'read_at'], name='messaging_m_user_id_b93c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipientstatus',
            index=models.Index(fields=['user', 'seen_at'], name='messaging_m_user_id_4f56d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagerecipientstatus',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_recipient_status'),
        ),
        migrations.AddIndex(
            model_name='messageuserstate',
            index=models.Index(fields=['message', 'user'], name='messaging_m_message_8345bb_idx'),
        ),
        migrations.AddIndex(
            model_name='messageuserstate',
            index=models.Index(fields=['user', 'deleted_for_me_at'], name='messaging_m_user_id_6cc96a_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageuserstate',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_user_state'),
        ),
    ]
