# Generated by Django 6.0.5 on 2026-05-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagerecipientstatus_messageuserstate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagerecipientstatus',
            options={'verbose_name': 'Message Recipient Status', 'verbose_name_plural': 'Message Recipient Statuses'},
        ),
        migrations.AlterModelOptions(
            name='messageuserstate',
            options={'verbose_name': 'Message User State', 'verbose_name_plural': 'Message User States'},
        ),
    ]
